name: Run

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 */3 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Checkout data
        uses: actions/checkout@v4
        with:
          ref: data
          path: yahoo_syndication/data
      - name: Run
        run: python -m yahoo_syndication.main
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
          YAHOO_FEED_URL: ${{ secrets.YAHOO_FEED_URL }}
          FROM_ADDRESS: ${{ secrets.FROM_ADDRESS }}
          FROM_PWD: ${{ secrets.FROM_PWD }}
          TO_ADDRESSES: ${{ secrets.TO_ADDRESSES }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          EMAIL_SENDING_ENABLED: false

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: yahoo_syndication/data
